// Generate typed event wire-types from the notify-service AsyncAPI 3.0.0
// contract. @hey-api/openapi-ts only reads OpenAPI, so the event side of the
// SDK is generated here: parse the AsyncAPI, pull each component schema's JSON
// Schema, and compile to TypeScript via json-schema-to-typescript.
//
// Output: src/events.gen.ts (committed; drift-guarded).
//
// NOTE (#306): the committed AsyncAPI uses the deprecated `nullable: true`
// keyword on display_name/deleted_at. AsyncAPI 3.0.0 (JSON Schema 2020-12) does
// NOT honor it, so those fields generate as `string` (not `string | null`). The
// types are correct against the producer's always-present envelope; the
// nullability narrows once #306 lands the 2020-12 `type: [..., "null"]` form and
// the service spec is regen-backfilled. Not a blocker — generation succeeds.

import { Parser } from '@asyncapi/parser';
import { compile } from 'json-schema-to-typescript';
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const asyncapiPath = resolve(
  here,
  '../../../services/notify-service/specs/notify.asyncapi.yaml',
);
const outPath = resolve(here, '../src/events.gen.ts');

const doc = readFileSync(asyncapiPath, 'utf8');
const { document, diagnostics } = await new Parser().parse(doc);
const errors = diagnostics.filter((d) => d.severity === 0);
if (errors.length > 0 || !document) {
  console.error('AsyncAPI parse failed with error-severity diagnostics:');
  for (const d of errors) console.error(`  ${d.code}: ${d.message}`);
  process.exit(1);
}

const banner = `// This file is auto-generated by scripts/gen-events.mjs from
// notify-service/specs/notify.asyncapi.yaml. Do NOT edit by hand — run
// \`bun run generate\` to refresh. Drift is enforced by test/drift.test.ts.
`;

const blocks = [];
for (const schema of document.components().schemas()) {
  const id = schema.id();
  const json = schema.json();
  const ts = await compile(json, id, {
    bannerComment: '',
    additionalProperties: false,
    format: false,
  });
  blocks.push(ts.trim());
}

const body = `${banner}\n${blocks.join('\n\n')}\n`;
writeFileSync(outPath, body);
console.log(`wrote ${outPath} (${blocks.length} event schema type(s))`);
