// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { NotifysHealthData, NotifysHealthErrors, NotifysHealthResponses, NotifysProtectedProbeData, NotifysProtectedProbeErrors, NotifysProtectedProbeResponses, NotifysProtectedWriteData, NotifysProtectedWriteErrors, NotifysProtectedWriteResponses, NotifysReadData, NotifysReadErrors, NotifysReadResponses, TemplatesCreateData, TemplatesCreateErrors, TemplatesCreateResponses, TemplatesListData, TemplatesListErrors, TemplatesListResponses, TemplatesReadData, TemplatesReadErrors, TemplatesReadResponses, TemplatesRemoveData, TemplatesRemoveErrors, TemplatesRemoveResponses, TemplatesRenderData, TemplatesRenderErrors, TemplatesRenderResponses, TemplatesUpdateData, TemplatesUpdateErrors, TemplatesUpdateResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * List authorable templates for the JWT tenant.
 */
export const templatesList = <ThrowOnError extends boolean = false>(options: Options<TemplatesListData, ThrowOnError>): RequestResult<TemplatesListResponses, TemplatesListErrors, ThrowOnError> => (options.client ?? client).get<TemplatesListResponses, TemplatesListErrors, ThrowOnError>({ url: '/notify/templates', ...options });

/**
 * Author a new template (tenant-admin).
 */
export const templatesCreate = <ThrowOnError extends boolean = false>(options: Options<TemplatesCreateData, ThrowOnError>): RequestResult<TemplatesCreateResponses, TemplatesCreateErrors, ThrowOnError> => (options.client ?? client).post<TemplatesCreateResponses, TemplatesCreateErrors, ThrowOnError>({
    url: '/notify/templates',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete a template (tenant-admin).
 */
export const templatesRemove = <ThrowOnError extends boolean = false>(options: Options<TemplatesRemoveData, ThrowOnError>): RequestResult<TemplatesRemoveResponses, TemplatesRemoveErrors, ThrowOnError> => (options.client ?? client).delete<TemplatesRemoveResponses, TemplatesRemoveErrors, ThrowOnError>({ url: '/notify/templates/{id}', ...options });

/**
 * Read one template by id (tenant-scoped; 404 if absent/foreign).
 */
export const templatesRead = <ThrowOnError extends boolean = false>(options: Options<TemplatesReadData, ThrowOnError>): RequestResult<TemplatesReadResponses, TemplatesReadErrors, ThrowOnError> => (options.client ?? client).get<TemplatesReadResponses, TemplatesReadErrors, ThrowOnError>({ url: '/notify/templates/{id}', ...options });

/**
 * Edit a template's authorable fields (tenant-admin).
 */
export const templatesUpdate = <ThrowOnError extends boolean = false>(options: Options<TemplatesUpdateData, ThrowOnError>): RequestResult<TemplatesUpdateResponses, TemplatesUpdateErrors, ThrowOnError> => (options.client ?? client).patch<TemplatesUpdateResponses, TemplatesUpdateErrors, ThrowOnError>({
    url: '/notify/templates/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Render a template by id against a context: {{var}} -> value.
 */
export const templatesRender = <ThrowOnError extends boolean = false>(options: Options<TemplatesRenderData, ThrowOnError>): RequestResult<TemplatesRenderResponses, TemplatesRenderErrors, ThrowOnError> => (options.client ?? client).post<TemplatesRenderResponses, TemplatesRenderErrors, ThrowOnError>({
    url: '/notify/templates/{id}/render',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Liveness probe.
 */
export const notifysHealth = <ThrowOnError extends boolean = false>(options?: Options<NotifysHealthData, ThrowOnError>): RequestResult<NotifysHealthResponses, NotifysHealthErrors, ThrowOnError> => (options?.client ?? client).get<NotifysHealthResponses, NotifysHealthErrors, ThrowOnError>({ url: '/notifys/health', ...options });

/**
 * Role-gated probe (clinician, tenant-admin).
 */
export const notifysProtectedProbe = <ThrowOnError extends boolean = false>(options?: Options<NotifysProtectedProbeData, ThrowOnError>): RequestResult<NotifysProtectedProbeResponses, NotifysProtectedProbeErrors, ThrowOnError> => (options?.client ?? client).get<NotifysProtectedProbeResponses, NotifysProtectedProbeErrors, ThrowOnError>({ url: '/notifys/protected', ...options });

/**
 * Demonstration write - actor bound to the JWT principal.
 */
export const notifysProtectedWrite = <ThrowOnError extends boolean = false>(options: Options<NotifysProtectedWriteData, ThrowOnError>): RequestResult<NotifysProtectedWriteResponses, NotifysProtectedWriteErrors, ThrowOnError> => (options.client ?? client).post<NotifysProtectedWriteResponses, NotifysProtectedWriteErrors, ThrowOnError>({
    url: '/notifys/protected-write',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Diamond-root scoped read by id.
 */
export const notifysRead = <ThrowOnError extends boolean = false>(options: Options<NotifysReadData, ThrowOnError>): RequestResult<NotifysReadResponses, NotifysReadErrors, ThrowOnError> => (options.client ?? client).get<NotifysReadResponses, NotifysReadErrors, ThrowOnError>({ url: '/notifys/{id}', ...options });
