// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://{host}/api/v1/notify' | 'http://localhost:3000' | (string & {});
};

/**
 * Liveness probe result — any authenticated principal may call it.
 */
export type HealthStatus = {
    status: string;
    layer: string;
};

/**
 * Scoped single-resource read result.
 */
export type NotifyRead = {
    id: string;
    status: string;
    layer: string;
    actorId: string;
};

export type NotifyWriteInput = {
    /**
     * Optional free-text reason captured on the write. Trimmed runtime-side by Zod.
     */
    reason?: string;
};

export type ProblemResponse = {
    statusCode?: number;
    status?: number;
    error?: string;
    message: string | Array<string>;
};

/**
 * Result of the demonstration write — actorId is the JWT-derived principal, never body-supplied.
 */
export type WriteAck = {
    status: string;
    layer: string;
    actorId: string;
};

export type NotifysHealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/notifys/health';
};

export type NotifysHealthErrors = {
    /**
     * Access is unauthorized.
     */
    401: ProblemResponse;
};

export type NotifysHealthError = NotifysHealthErrors[keyof NotifysHealthErrors];

export type NotifysHealthResponses = {
    /**
     * The request has succeeded.
     */
    200: HealthStatus;
};

export type NotifysHealthResponse = NotifysHealthResponses[keyof NotifysHealthResponses];

export type NotifysProtectedProbeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/notifys/protected';
};

export type NotifysProtectedProbeErrors = {
    /**
     * Access is unauthorized.
     */
    401: ProblemResponse;
    /**
     * Access is forbidden.
     */
    403: ProblemResponse;
};

export type NotifysProtectedProbeError = NotifysProtectedProbeErrors[keyof NotifysProtectedProbeErrors];

export type NotifysProtectedProbeResponses = {
    /**
     * The request has succeeded.
     */
    200: HealthStatus;
};

export type NotifysProtectedProbeResponse = NotifysProtectedProbeResponses[keyof NotifysProtectedProbeResponses];

export type NotifysProtectedWriteData = {
    body: NotifyWriteInput;
    headers: {
        Authorization: string;
    };
    path?: never;
    query?: never;
    url: '/notifys/protected-write';
};

export type NotifysProtectedWriteErrors = {
    /**
     * The server could not understand the request due to invalid syntax.
     */
    400: ProblemResponse;
    /**
     * Access is unauthorized.
     */
    401: ProblemResponse;
    /**
     * Access is forbidden.
     */
    403: ProblemResponse;
};

export type NotifysProtectedWriteError = NotifysProtectedWriteErrors[keyof NotifysProtectedWriteErrors];

export type NotifysProtectedWriteResponses = {
    /**
     * The request has succeeded.
     */
    200: WriteAck;
};

export type NotifysProtectedWriteResponse = NotifysProtectedWriteResponses[keyof NotifysProtectedWriteResponses];

export type NotifysReadData = {
    body?: never;
    headers: {
        Authorization: string;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/notifys/{id}';
};

export type NotifysReadErrors = {
    /**
     * Access is unauthorized.
     */
    401: ProblemResponse;
    /**
     * Access is forbidden.
     */
    403: ProblemResponse;
    /**
     * The server cannot find the requested resource.
     */
    404: ProblemResponse;
};

export type NotifysReadError = NotifysReadErrors[keyof NotifysReadErrors];

export type NotifysReadResponses = {
    /**
     * The request has succeeded.
     */
    200: NotifyRead;
};

export type NotifysReadResponse = NotifysReadResponses[keyof NotifysReadResponses];
